// Mocks generated by Mockito 5.2.0 from annotations
// in cinta_film/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i23;
import 'dart:convert' as _i34;
import 'dart:typed_data' as _i35;

import 'package:bloc/bloc.dart' as _i33;
import 'package:cinta_film/common/failure.dart' as _i24;
import 'package:cinta_film/data/datasources/db/database_helper.dart' as _i31;
import 'package:cinta_film/data/datasources/film/movie_local_data_source.dart'
    as _i29;
import 'package:cinta_film/data/datasources/film/movie_remote_data_source.dart'
    as _i27;
import 'package:cinta_film/data/models/movie_detail_model.dart' as _i3;
import 'package:cinta_film/data/models/movie_model.dart' as _i28;
import 'package:cinta_film/data/models/movie_table.dart' as _i30;
import 'package:cinta_film/domain/entities/film.dart' as _i25;
import 'package:cinta_film/domain/entities/movie_detail.dart' as _i26;
import 'package:cinta_film/domain/repositories/movie_repository.dart' as _i4;
import 'package:cinta_film/domain/usecases/ambil_daftar_tonton_film.dart'
    as _i18;
import 'package:cinta_film/domain/usecases/ambil_data_detail_film.dart' as _i15;
import 'package:cinta_film/domain/usecases/ambil_data_film_rating_terbaik.dart'
    as _i11;
import 'package:cinta_film/domain/usecases/ambil_data_film_rekomendasi.dart'
    as _i9;
import 'package:cinta_film/domain/usecases/ambil_data_film_terpopuler.dart'
    as _i5;
import 'package:cinta_film/domain/usecases/ambil_data_tayang_saat_ini.dart'
    as _i7;
import 'package:cinta_film/domain/usecases/ambil_status_daftar_tonton.dart'
    as _i17;
import 'package:cinta_film/domain/usecases/cari_film.dart' as _i13;
import 'package:cinta_film/domain/usecases/daftar_tonton.dart' as _i20;
import 'package:cinta_film/domain/usecases/hapus_daftar_tonton.dart' as _i19;
import 'package:cinta_film/presentasi/bloc/film_daftar_tonton_bloc/movie_watchlist_bloc.dart'
    as _i21;
import 'package:cinta_film/presentasi/bloc/film_detail_bloc/movie_detail_bloc.dart'
    as _i16;
import 'package:cinta_film/presentasi/bloc/film_pencarian_bloc/movie_search_bloc.dart'
    as _i14;
import 'package:cinta_film/presentasi/bloc/film_rating_terbaik_bloc/movie_top_rated_bloc.dart'
    as _i12;
import 'package:cinta_film/presentasi/bloc/film_rekomendasi_bloc/movie_recommendation_bloc.dart'
    as _i10;
import 'package:cinta_film/presentasi/bloc/film_saat_ini_tayang_bloc/movie_now_playing_bloc.dart'
    as _i8;
import 'package:cinta_film/presentasi/bloc/film_terpopuler_bloc/movie_popular_bloc.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i22;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i32;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieDetailResponse_1 extends _i1.Fake
    implements _i3.MovieDetailResponse {}

class _FakeRepositoryFilm_2 extends _i1.Fake implements _i4.RepositoryFilm {}

class _FakeClassFilmTerPopuler_3 extends _i1.Fake
    implements _i5.ClassFilmTerPopuler {}

class _FakeMoviePopularState_4 extends _i1.Fake
    implements _i6.MoviePopularState {}

class _FakeClasFilmTayangSaatIni_5 extends _i1.Fake
    implements _i7.ClasFilmTayangSaatIni {}

class _FakeMovieNowPlayingState_6 extends _i1.Fake
    implements _i8.MovieNowPlayingState {}

class _FakeAmbilDataRekomendasiFilm_7 extends _i1.Fake
    implements _i9.AmbilDataRekomendasiFilm {}

class _FakeMovieRecommendationState_8 extends _i1.Fake
    implements _i10.MovieRecommendationState {}

class _FakeClassFilmRatingTerbaik_9 extends _i1.Fake
    implements _i11.ClassFilmRatingTerbaik {}

class _FakeMovieTopRatedState_10 extends _i1.Fake
    implements _i12.MovieTopRatedState {}

class _FakeClassCariFilm_11 extends _i1.Fake implements _i13.ClassCariFilm {}

class _FakeMovieSearchState_12 extends _i1.Fake
    implements _i14.MovieSearchState {}

class _FakeGetMovieDetail_13 extends _i1.Fake implements _i15.GetMovieDetail {}

class _FakeMovieDetailState_14 extends _i1.Fake
    implements _i16.MovieDetailState {}

class _FakeClassStatusDaftarTonton_15 extends _i1.Fake
    implements _i17.ClassStatusDaftarTonton {}

class _FakeClassDaftarTontonFilm_16 extends _i1.Fake
    implements _i18.ClassDaftarTontonFilm {}

class _FakeClassHapusDaftarTonton_17 extends _i1.Fake
    implements _i19.ClassHapusDaftarTonton {}

class _FakeClassSimpanDaftarTonton_18 extends _i1.Fake
    implements _i20.ClassSimpanDaftarTonton {}

class _FakeMovieWatchlistState_19 extends _i1.Fake
    implements _i21.MovieWatchlistState {}

class _FakeResponse_20 extends _i1.Fake implements _i22.Response {}

class _FakeStreamedResponse_21 extends _i1.Fake
    implements _i22.StreamedResponse {}

/// A class which mocks [RepositoryFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepositoryFilm extends _i1.Mock implements _i4.RepositoryFilm {
  MockRepositoryFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> filmTayangSaatIni() =>
      (super.noSuchMethod(Invocation.method(#filmTayangSaatIni, []),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>>
      ambilDataFilmTerPopuler() =>
          (super.noSuchMethod(Invocation.method(#ambilDataFilmTerPopuler, []),
                  returnValue:
                      Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
                          _FakeEither_0<_i24.Failure, List<_i25.Film>>()))
              as _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>>
      ambilFilmRatingTerbaik() =>
          (super.noSuchMethod(Invocation.method(#ambilFilmRatingTerbaik, []),
                  returnValue:
                      Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
                          _FakeEither_0<_i24.Failure, List<_i25.Film>>()))
              as _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, _i26.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i24.Failure, _i26.MovieDetail>>.value(
              _FakeEither_0<_i24.Failure, _i26.MovieDetail>())) as _i23
          .Future<_i2.Either<_i24.Failure, _i26.MovieDetail>>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
          Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> cariFilm(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#cariFilm, [query]),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, String>> daftarTonton(
          _i26.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#daftarTonton, [film]),
              returnValue: Future<_i2.Either<_i24.Failure, String>>.value(
                  _FakeEither_0<_i24.Failure, String>()))
          as _i23.Future<_i2.Either<_i24.Failure, String>>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, String>> removewatchlist(
          _i26.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
              returnValue: Future<_i2.Either<_i24.Failure, String>>.value(
                  _FakeEither_0<_i24.Failure, String>()))
          as _i23.Future<_i2.Either<_i24.Failure, String>>);
  @override
  _i23.Future<bool> isAddedTowatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedTowatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i23.Future<bool>);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>>
      ambilDaftarTontonFilm() =>
          (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
                  returnValue:
                      Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
                          _FakeEither_0<_i24.Failure, List<_i25.Film>>()))
              as _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i27.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.Future<List<_i28.MovieModel>> filmTayangSaatIni() => (super.noSuchMethod(
          Invocation.method(#filmTayangSaatIni, []),
          returnValue: Future<List<_i28.MovieModel>>.value(<_i28.MovieModel>[]))
      as _i23.Future<List<_i28.MovieModel>>);
  @override
  _i23.Future<List<_i28.MovieModel>> ambilDataFilmTerPopuler() =>
      (super.noSuchMethod(Invocation.method(#ambilDataFilmTerPopuler, []),
              returnValue:
                  Future<List<_i28.MovieModel>>.value(<_i28.MovieModel>[]))
          as _i23.Future<List<_i28.MovieModel>>);
  @override
  _i23.Future<List<_i28.MovieModel>> ambilFilmRatingTerbaik() =>
      (super.noSuchMethod(Invocation.method(#ambilFilmRatingTerbaik, []),
              returnValue:
                  Future<List<_i28.MovieModel>>.value(<_i28.MovieModel>[]))
          as _i23.Future<List<_i28.MovieModel>>);
  @override
  _i23.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1()))
          as _i23.Future<_i3.MovieDetailResponse>);
  @override
  _i23.Future<List<_i28.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i28.MovieModel>>.value(<_i28.MovieModel>[]))
          as _i23.Future<List<_i28.MovieModel>>);
  @override
  _i23.Future<List<_i28.MovieModel>> cariFilm(String? query) =>
      (super.noSuchMethod(Invocation.method(#cariFilm, [query]),
              returnValue:
                  Future<List<_i28.MovieModel>>.value(<_i28.MovieModel>[]))
          as _i23.Future<List<_i28.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i29.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.Future<String> insertwatchlist(_i30.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlist, [film]),
          returnValue: Future<String>.value('')) as _i23.Future<String>);
  @override
  _i23.Future<String> removewatchlist(_i30.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
          returnValue: Future<String>.value('')) as _i23.Future<String>);
  @override
  _i23.Future<_i30.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i30.MovieTable?>.value())
          as _i23.Future<_i30.MovieTable?>);
  @override
  _i23.Future<List<_i30.MovieTable>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
              returnValue:
                  Future<List<_i30.MovieTable>>.value(<_i30.MovieTable>[]))
          as _i23.Future<List<_i30.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i31.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.Future<_i32.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i32.Database?>.value())
          as _i23.Future<_i32.Database?>);
  @override
  _i23.Future<int> insertwatchlist(_i30.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlist, [film]),
          returnValue: Future<int>.value(0)) as _i23.Future<int>);
  @override
  _i23.Future<int> removewatchlist(_i30.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
          returnValue: Future<int>.value(0)) as _i23.Future<int>);
  @override
  _i23.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i23.Future<Map<String, dynamic>?>);
  @override
  _i23.Future<List<Map<String, dynamic>>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i23.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [ClassDaftarTontonFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassDaftarTontonFilm extends _i1.Mock
    implements _i18.ClassDaftarTontonFilm {
  MockClassDaftarTontonFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i15.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, _i26.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i24.Failure, _i26.MovieDetail>>.value(
              _FakeEither_0<_i24.Failure, _i26.MovieDetail>())) as _i23
          .Future<_i2.Either<_i24.Failure, _i26.MovieDetail>>);
}

/// A class which mocks [ClassFilmRatingTerbaik].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassFilmRatingTerbaik extends _i1.Mock
    implements _i11.ClassFilmRatingTerbaik {
  MockClassFilmRatingTerbaik() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
}

/// A class which mocks [AmbilDataRekomendasiFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmbilDataRekomendasiFilm extends _i1.Mock
    implements _i9.AmbilDataRekomendasiFilm {
  MockAmbilDataRekomendasiFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
}

/// A class which mocks [ClassFilmTerPopuler].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassFilmTerPopuler extends _i1.Mock
    implements _i5.ClassFilmTerPopuler {
  MockClassFilmTerPopuler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
}

/// A class which mocks [ClasFilmTayangSaatIni].
///
/// See the documentation for Mockito's code generation for more information.
class MockClasFilmTayangSaatIni extends _i1.Mock
    implements _i7.ClasFilmTayangSaatIni {
  MockClasFilmTayangSaatIni() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
}

/// A class which mocks [ClassStatusDaftarTonton].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassStatusDaftarTonton extends _i1.Mock
    implements _i17.ClassStatusDaftarTonton {
  MockClassStatusDaftarTonton() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i23.Future<bool>);
}

/// A class which mocks [ClassCariFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassCariFilm extends _i1.Mock implements _i13.ClassCariFilm {
  MockClassCariFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, List<_i25.Film>>> execute(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
          returnValue: Future<_i2.Either<_i24.Failure, List<_i25.Film>>>.value(
              _FakeEither_0<_i24.Failure, List<_i25.Film>>())) as _i23
          .Future<_i2.Either<_i24.Failure, List<_i25.Film>>>);
}

/// A class which mocks [ClassSimpanDaftarTonton].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassSimpanDaftarTonton extends _i1.Mock
    implements _i20.ClassSimpanDaftarTonton {
  MockClassSimpanDaftarTonton() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, String>> execute(
          _i26.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#execute, [film]),
              returnValue: Future<_i2.Either<_i24.Failure, String>>.value(
                  _FakeEither_0<_i24.Failure, String>()))
          as _i23.Future<_i2.Either<_i24.Failure, String>>);
}

/// A class which mocks [ClassHapusDaftarTonton].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassHapusDaftarTonton extends _i1.Mock
    implements _i19.ClassHapusDaftarTonton {
  MockClassHapusDaftarTonton() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i23.Future<_i2.Either<_i24.Failure, String>> execute(
          _i26.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#execute, [film]),
              returnValue: Future<_i2.Either<_i24.Failure, String>>.value(
                  _FakeEither_0<_i24.Failure, String>()))
          as _i23.Future<_i2.Either<_i24.Failure, String>>);
}

/// A class which mocks [MoviePopularBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviePopularBloc extends _i1.Mock implements _i6.MoviePopularBloc {
  MockMoviePopularBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ClassFilmTerPopuler get getPopularMovies => (super.noSuchMethod(
      Invocation.getter(#getPopularMovies),
      returnValue: _FakeClassFilmTerPopuler_3()) as _i5.ClassFilmTerPopuler);
  @override
  _i6.MoviePopularState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeMoviePopularState_4()) as _i6.MoviePopularState);
  @override
  _i23.Stream<_i6.MoviePopularState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.MoviePopularState>.empty())
          as _i23.Stream<_i6.MoviePopularState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.MoviePopularEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.MoviePopularEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.MoviePopularState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.MoviePopularEvent>(
          _i33.EventHandler<E, _i6.MoviePopularState>? handler,
          {_i33.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i33.Transition<_i6.MoviePopularEvent, _i6.MoviePopularState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i23.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i23.Future<void>);
  @override
  void onChange(_i33.Change<_i6.MoviePopularState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieNowPlayingBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieNowPlayingBloc extends _i1.Mock
    implements _i8.MovieNowPlayingBloc {
  MockMovieNowPlayingBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ClasFilmTayangSaatIni get getNowPlayingMovies =>
      (super.noSuchMethod(Invocation.getter(#getNowPlayingMovies),
              returnValue: _FakeClasFilmTayangSaatIni_5())
          as _i7.ClasFilmTayangSaatIni);
  @override
  _i8.MovieNowPlayingState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeMovieNowPlayingState_6()) as _i8.MovieNowPlayingState);
  @override
  _i23.Stream<_i8.MovieNowPlayingState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i8.MovieNowPlayingState>.empty())
          as _i23.Stream<_i8.MovieNowPlayingState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i8.MovieNowPlayingEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i8.MovieNowPlayingEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i8.MovieNowPlayingState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i8.MovieNowPlayingEvent>(
          _i33.EventHandler<E, _i8.MovieNowPlayingState>? handler,
          {_i33.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i33.Transition<_i8.MovieNowPlayingEvent, _i8.MovieNowPlayingState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i23.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i23.Future<void>);
  @override
  void onChange(_i33.Change<_i8.MovieNowPlayingState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieRecommendationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRecommendationBloc extends _i1.Mock
    implements _i10.MovieRecommendationBloc {
  MockMovieRecommendationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AmbilDataRekomendasiFilm get getMovieRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getMovieRecommendations),
              returnValue: _FakeAmbilDataRekomendasiFilm_7())
          as _i9.AmbilDataRekomendasiFilm);
  @override
  _i10.MovieRecommendationState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeMovieRecommendationState_8())
          as _i10.MovieRecommendationState);
  @override
  _i23.Stream<_i10.MovieRecommendationState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i10.MovieRecommendationState>.empty())
          as _i23.Stream<_i10.MovieRecommendationState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i10.MovieRecommendationEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i10.MovieRecommendationEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i10.MovieRecommendationState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i10.MovieRecommendationEvent>(
          _i33.EventHandler<E, _i10.MovieRecommendationState>? handler,
          {_i33.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i33.Transition<_i10.MovieRecommendationEvent,
                  _i10.MovieRecommendationState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i23.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i23.Future<void>);
  @override
  void onChange(_i33.Change<_i10.MovieRecommendationState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieTopRatedBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieTopRatedBloc extends _i1.Mock implements _i12.MovieTopRatedBloc {
  MockMovieTopRatedBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.ClassFilmRatingTerbaik get getTopRatedMovies =>
      (super.noSuchMethod(Invocation.getter(#getTopRatedMovies),
              returnValue: _FakeClassFilmRatingTerbaik_9())
          as _i11.ClassFilmRatingTerbaik);
  @override
  _i12.MovieTopRatedState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeMovieTopRatedState_10()) as _i12.MovieTopRatedState);
  @override
  _i23.Stream<_i12.MovieTopRatedState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i12.MovieTopRatedState>.empty())
          as _i23.Stream<_i12.MovieTopRatedState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i12.MovieTopRatedEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i12.MovieTopRatedEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i12.MovieTopRatedState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i12.MovieTopRatedEvent>(
          _i33.EventHandler<E, _i12.MovieTopRatedState>? handler,
          {_i33.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i33.Transition<_i12.MovieTopRatedEvent, _i12.MovieTopRatedState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i23.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i23.Future<void>);
  @override
  void onChange(_i33.Change<_i12.MovieTopRatedState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchBloc extends _i1.Mock implements _i14.MovieSearchBloc {
  MockMovieSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.ClassCariFilm get searchMovies =>
      (super.noSuchMethod(Invocation.getter(#searchMovies),
          returnValue: _FakeClassCariFilm_11()) as _i13.ClassCariFilm);
  @override
  _i14.MovieSearchState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeMovieSearchState_12()) as _i14.MovieSearchState);
  @override
  _i23.Stream<_i14.MovieSearchState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i14.MovieSearchState>.empty())
          as _i23.Stream<_i14.MovieSearchState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i14.MovieSearchEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i14.MovieSearchEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i14.MovieSearchState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i14.MovieSearchEvent>(
          _i33.EventHandler<E, _i14.MovieSearchState>? handler,
          {_i33.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i33.Transition<_i14.MovieSearchEvent, _i14.MovieSearchState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i23.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i23.Future<void>);
  @override
  void onChange(_i33.Change<_i14.MovieSearchState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailBloc extends _i1.Mock implements _i16.MovieDetailBloc {
  MockMovieDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.GetMovieDetail get getMovieDetail =>
      (super.noSuchMethod(Invocation.getter(#getMovieDetail),
          returnValue: _FakeGetMovieDetail_13()) as _i15.GetMovieDetail);
  @override
  _i16.MovieDetailState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeMovieDetailState_14()) as _i16.MovieDetailState);
  @override
  _i23.Stream<_i16.MovieDetailState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i16.MovieDetailState>.empty())
          as _i23.Stream<_i16.MovieDetailState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i16.MovieDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i16.MovieDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i16.MovieDetailState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i16.MovieDetailEvent>(
          _i33.EventHandler<E, _i16.MovieDetailState>? handler,
          {_i33.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i33.Transition<_i16.MovieDetailEvent, _i16.MovieDetailState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i23.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i23.Future<void>);
  @override
  void onChange(_i33.Change<_i16.MovieDetailState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieWatchlistBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieWatchlistBloc extends _i1.Mock
    implements _i21.MovieWatchlistBloc {
  MockMovieWatchlistBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.ClassStatusDaftarTonton get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeClassStatusDaftarTonton_15())
          as _i17.ClassStatusDaftarTonton);
  @override
  _i18.ClassDaftarTontonFilm get getWatchlistMovies =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistMovies),
              returnValue: _FakeClassDaftarTontonFilm_16())
          as _i18.ClassDaftarTontonFilm);
  @override
  _i19.ClassHapusDaftarTonton get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeClassHapusDaftarTonton_17())
          as _i19.ClassHapusDaftarTonton);
  @override
  _i20.ClassSimpanDaftarTonton get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
              returnValue: _FakeClassSimpanDaftarTonton_18())
          as _i20.ClassSimpanDaftarTonton);
  @override
  _i21.MovieWatchlistState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeMovieWatchlistState_19()) as _i21.MovieWatchlistState);
  @override
  _i23.Stream<_i21.MovieWatchlistState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i21.MovieWatchlistState>.empty())
          as _i23.Stream<_i21.MovieWatchlistState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i21.MovieWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i21.MovieWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i21.MovieWatchlistState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i21.MovieWatchlistEvent>(
          _i33.EventHandler<E, _i21.MovieWatchlistState>? handler,
          {_i33.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i33.Transition<_i21.MovieWatchlistEvent, _i21.MovieWatchlistState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i23.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i23.Future<void>);
  @override
  void onChange(_i33.Change<_i21.MovieWatchlistState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i22.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.Future<_i22.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i22.Response>.value(_FakeResponse_20()))
          as _i23.Future<_i22.Response>);
  @override
  _i23.Future<_i22.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i22.Response>.value(_FakeResponse_20()))
          as _i23.Future<_i22.Response>);
  @override
  _i23.Future<_i22.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i34.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i22.Response>.value(_FakeResponse_20()))
          as _i23.Future<_i22.Response>);
  @override
  _i23.Future<_i22.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i34.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i22.Response>.value(_FakeResponse_20()))
          as _i23.Future<_i22.Response>);
  @override
  _i23.Future<_i22.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i34.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i22.Response>.value(_FakeResponse_20()))
          as _i23.Future<_i22.Response>);
  @override
  _i23.Future<_i22.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i34.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i22.Response>.value(_FakeResponse_20()))
          as _i23.Future<_i22.Response>);
  @override
  _i23.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i23.Future<String>);
  @override
  _i23.Future<_i35.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i35.Uint8List>.value(_i35.Uint8List(0)))
          as _i23.Future<_i35.Uint8List>);
  @override
  _i23.Future<_i22.StreamedResponse> send(_i22.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: Future<_i22.StreamedResponse>.value(
                  _FakeStreamedResponse_21()))
          as _i23.Future<_i22.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
